### ISSUE TITLE
Gentoo on Framework

### ISSUE THREAD

**Issue by catvec** [Noah-Huppert/linux-install#33]
Some modifications need to made to make this repo work for my new laptop:

- bootstrap
  - modify for Gentoo iso
  - ntp
  - stage 3
  - chroot mounts have different options
    - https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Mounting_the_necessary_filesystems
  - ~~portage config~~ (in salt now)
    - `/etc/portage/make.conf`
    - `COMMON_FLAGS="-march=native -O2 -pipe"` (https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Stage#CFLAGS_and_CXXFLAGS)
    -  [mirror selection](https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Optional:_Selecting_mirrors)
    - [licenses](https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Optional:_Configure_the_ACCEPT_LICENSE_variable), `ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"`
    - `USE="cryptsetup"`
  - ~~select kernel~~ (in salt now)
    - `eselect kernel set 1`
  - kernel
    - https://wiki.gentoo.org/wiki/Systemd#Kernel
    - ~~options `/usr/src/linux/.config`~~ (in salt now)
    - build
  - systemd setup
    - [mtab symlink](https://wiki.gentoo.org/wiki/Systemd#.2Fetc.2Fmtab)
    - [first time setup command](https://wiki.gentoo.org/wiki/Systemd#Configuration)
  - configure boot
    - genkernel
      - install
      - ~~`/etc/genkernel.conf`: luks yes, install yes~~ (in salt now)
    - [disk encryption and initramfs](https://wiki.gentoo.org/wiki/Systemd#Using_LVM_and_initramfs)
    - ~~[refind](https://wiki.gentoo.org/wiki/Refind)~~ (in salt now)
      - install `sys-boot/refind sys-boot/efibootmgr`
      - `refind-install`
      - boot options `crypt_root=UUID=<part UUID>`
- networking
  - `net-wireless/iw`
  - `net-wireless/wpa_supplicant`
    - add `/etc/wpa_supplicant-wlp166s0.conf`
    - add `/etc/systemd/network/00-wireless.network`
      ```
      [Match]
      Name=wlp166s0
      
      [Network]
      DHCP=yes
      IgnoreCarrierLoss=3s
      ```
    - `systemctl enable --now wpa_supplicant@wlp166s0`
- salt
    - `app-admin/salt` (`echo "app-admin/salt portage" >> /etc/portage/package.use/salt`, `echo "net-libs/zeromq drafts" >> /etc/portage/package.use/salt`)
    - `/etc/salt/minion`:
      ```
      saltenv: gentoo
      pillarenv: gentoo

      file_roots:
        base:
          - /srv/salt/base
      pillar_roots:
        base:
          - /srv/pillar/base
      ext_pillar:
        - stack:
            pillar:environment:
              base:
                - /srv/pillar/base/pillar-stack.cfg
      ```
- ~~utilities~~ (in salt now)
  - `e-file` for searching packages by file (`app-portage/pfl`, `echo "sys-apps/util-linux caps" > /etc/portage/package.use/pfl`)

Changes to this repo should be made in a way that the original void linux support is not lost. But instead an ability to select between gentoo and void is created.
